/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddAdmin: typeof import('./src/components/admin/dialog/addAdmin.vue')['default']
    AddNewCountry: typeof import('./src/components/country/dialog/addNewCountry.vue')['default']
    AddNewDelegates: typeof import('./src/components/Delegates/dialog/addNewDelegates.vue')['default']
    AddSpecialites: typeof import('./src/components/specialties/dialog/addSpecialites.vue')['default']
    AllLoading: typeof import('./src/components/loading/allLoading.vue')['default']
    AllOrderTable: typeof import('./src/components/order/table/AllOrderTable.vue')['default']
    AllPharmacyTable: typeof import('./src/components/pharmacy/tables/AllPharmacyTable.vue')['default']
    AllPillTable: typeof import('./src/components/pharmacy/tables/AllPillTable.vue')['default']
    AllPillTableExpired: typeof import('./src/components/expired/table/AllPillTableExpired.vue')['default']
    CardAdmin: typeof import('./src/components/admin/card/cardAdmin.vue')['default']
    CardDelegates: typeof import('./src/components/Delegates/card/CardDelegates.vue')['default']
    CardDetilsOrder: typeof import('./src/components/order/Card/CardDetilsOrder.vue')['default']
    CardHome: typeof import('./src/components/home/card/cardHome.vue')['default']
    CardNotifcation: typeof import('./src/components/TopUser/cardNotifcation.vue')['default']
    CardOrder: typeof import('./src/components/order/Card/CardOrder.vue')['default']
    CardPharmcy: typeof import('./src/components/pharmacy/card/cardPharmcy.vue')['default']
    CardShowPharmcy: typeof import('./src/components/pharmacy/card/CardShowPharmcy.vue')['default']
    ConfDialog: typeof import('./src/components/GlobalDialog/ConfDialog.vue')['default']
    EditAdmin: typeof import('./src/components/admin/dialog/editAdmin.vue')['default']
    EditCountry: typeof import('./src/components/country/dialog/editCountry.vue')['default']
    EditDelegates: typeof import('./src/components/Delegates/dialog/editDelegates.vue')['default']
    EditPharmcy: typeof import('./src/components/pharmacy/dialog/editPharmcy.vue')['default']
    EditSpecialites: typeof import('./src/components/specialties/dialog/editSpecialites.vue')['default']
    FiltersAllPharmcy: typeof import('./src/components/pharmacy/filters/FiltersAllPharmcy.vue')['default']
    FiltersOrder: typeof import('./src/components/order/filters/filtersOrder.vue')['default']
    FiltersPharmcyStoped: typeof import('./src/components/pharmacy/filters/FiltersPharmcyStoped.vue')['default']
    FitersSpeci: typeof import('./src/components/specialties/filters/fitersSpeci.vue')['default']
    HomeTable: typeof import('./src/components/home/table/homeTable.vue')['default']
    InformationMedical: typeof import('./src/components/pharmacy/card/informationMedical.vue')['default']
    LinksNavbar: typeof import('./src/components/navbar/linksNavbar.vue')['default']
    LogoNavbar: typeof import('./src/components/navbar/LogoNavbar.vue')['default']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    Pagination: typeof import('./src/components/pagination/pagination.vue')['default']
    ProductFilters: typeof import('./src/components/product/filters/productFilters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowCertification: typeof import('./src/components/pharmacy/dialog/showCertification.vue')['default']
    ShowMap: typeof import('./src/components/country/card/showMap.vue')['default']
    TableCountry: typeof import('./src/components/country/table/tableCountry.vue')['default']
    TableSpecialites: typeof import('./src/components/specialties/table/tableSpecialites.vue')['default']
    TopUser: typeof import('./src/components/TopUser/topUser.vue')['default']
  }
}
